"""update scenario table with index

Revision ID: 0ae1a916ba74
Revises: c38b6db78523
Create Date: 2026-03-24 19:23:20.204918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae1a916ba74'
down_revision: Union[str, Sequence[str], None] = 'c38b6db78523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('scenario_index', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_scenario_module_name'), 'scenario', type_='unique')
    op.create_unique_constraint('uq__module_scenario_index', 'scenario', ['module_id', 'scenario_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq__module_scenario_index', 'scenario', type_='unique')
    op.create_unique_constraint(op.f('uq_scenario_module_name'), 'scenario', ['module_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('scenario', 'scenario_index')
    # ### end Alembic commands ###
