"""update schema

Revision ID: 7f877a1abdaf
Revises: 
Create Date: 2026-03-15 15:49:37.234844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f877a1abdaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session', sa.Column('session_token', sa.String(), nullable=False))
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='role'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', name='role'),
               nullable=True)
    op.drop_column('training_session', 'session_token')
    # ### end Alembic commands ###
