"""update schema

Revision ID: 9a711bb01dc4
Revises: 7f877a1abdaf
Create Date: 2026-03-15 17:02:02.156957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a711bb01dc4'
down_revision: Union[str, Sequence[str], None] = '7f877a1abdaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_module', sa.Column('version', sa.String(), nullable=False))
    op.add_column('training_module', sa.Column('cdn_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_module', 'cdn_url')
    op.drop_column('training_module', 'version')
    # ### end Alembic commands ###
